# Generated by Django 4.2.16 on 2026-05-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Machine-readable action key, e.g. "donation.created"', max_length=100)),
                ('object_type', models.CharField(blank=True, help_text='Type of object affected, e.g. "Donation"', max_length=100)),
                ('object_id', models.BigIntegerField(blank=True, help_text='Primary key of the affected object', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable summary of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request (IPv4 or IPv6)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. NULL for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'), models.Index(fields=['object_type'], name='core_auditl_object__8d9be4_idx'), models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx')],
            },
        ),
    ]
