# Generated by Django 4.2.16 on 2026-05-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_code', models.CharField(editable=False, help_text='Auto-generated code: BEN-YYYY-NNNN', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/')),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_grade', models.CharField(blank=True, max_length=50)),
                ('health_status', models.TextField(blank=True, help_text='Current health conditions or notes')),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_relationship', models.CharField(blank=True, help_text='e.g., Aunt, Uncle, Grandmother', max_length=50)),
                ('location_region', models.CharField(blank=True, max_length=100)),
                ('location_district', models.CharField(blank=True, max_length=100)),
                ('date_enrolled', models.DateField(help_text='Date beneficiary was enrolled in the program')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this beneficiary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(help_text='Staff member who registered this beneficiary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-date_enrolled'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Progress narrative for donors')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo to accompany the update', null=True, upload_to='beneficiary_updates/')),
                ('notified_donors', models.BooleanField(default=False, help_text='Whether linked donors have been notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='beneficiaries.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ref', models.CharField(editable=False, help_text='Auto-generated: REQ-YYYY-NNNN', max_length=30, unique=True)),
                ('request_type', models.CharField(choices=[('education', 'Education'), ('food', 'Food'), ('medical', 'Medical'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the need')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in TZS', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='beneficiaries.beneficiary')),
                ('requested_by', models.ForeignKey(help_text='Staff member who submitted this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorBeneficiaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='NULL means currently active sponsorship', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_links', to='beneficiaries.beneficiary')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_beneficiaries', to='donors.donor')),
            ],
            options={
                'verbose_name': 'Donor-Beneficiary Link',
                'verbose_name_plural': 'Donor-Beneficiary Links',
                'unique_together': {('donor', 'beneficiary')},
            },
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['status'], name='beneficiari_status_ff1fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['beneficiary_code'], name='beneficiari_benefic_89f95d_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['location_region'], name='beneficiari_locatio_4813d5_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['beneficiary'], name='beneficiari_benefic_20eb15_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['status'], name='beneficiari_status_3189ba_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['request_type'], name='beneficiari_request_bcbcdf_idx'),
        ),
    ]
