# Generated by Django 4.2.16 on 2026-05-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_ref', models.CharField(editable=False, help_text='Auto-generated: DON-YYYY-NNNNN', max_length=30, unique=True)),
                ('donation_type', models.CharField(choices=[('cash', 'Cash'), ('in_kind', 'In-Kind')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Donation amount in TZS (if cash)', max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=30)),
                ('transaction_reference', models.CharField(blank=True, help_text='Mobile money or bank reference number', max_length=100)),
                ('in_kind_description', models.TextField(blank=True, help_text='Description of physical items donated')),
                ('in_kind_estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value in TZS (optional)', max_digits=12, null=True)),
                ('donation_date', models.DateField()),
                ('purpose', models.CharField(blank=True, help_text='e.g., Education Fund, General Fund', max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('partial', 'Partially Allocated'), ('allocated', 'Fully Allocated')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, help_text='NULL indicates an anonymous/unregistered donor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.donor')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_type', models.CharField(choices=[('education', 'Education'), ('food', 'Food'), ('medical', 'Medical'), ('clothing', 'Clothing'), ('general', 'General Operations')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_allocations', to=settings.AUTH_USER_MODEL)),
                ('assistance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='beneficiaries.assistancerequest')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='beneficiaries.beneficiary')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='donations.donation')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='donations_d_donatio_a63beb_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_type'], name='donations_d_donatio_5e5d0e_idx'),
        ),
    ]
