# Generated by Django 4.2.16 on 2026-05-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, help_text='Organization name (for corporate donors)', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Mailing address')),
                ('national_id', models.CharField(blank=True, help_text='National ID for tax receipt purposes', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name in public listings')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this donor (admin only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='The User account this donor profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
            },
        ),
    ]
